name: GitHub Repo Search

on:
  workflow_dispatch:
    inputs:
      keywords:
        description: 'Comma-separated keywords to search'
        required: true
        default: 'deepseek,deep seek'
      min_stars:
        description: "Minimum number of stars a repo should have"
        required: false
        default: "10"
      min_forks:
        description: "Minimum number of forks a repo should have"
        required: false
        default: "10"
      output_file:
        description: 'Output JSON file path'
        required: false
        default: 'results/data.json'

jobs:
  search-github-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run GitHub repo search script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python githubrepos.py \
            --keywords "${{ github.event.inputs.keywords }}" \
            --min-stars "${{ github.event.inputs.min_stars }}" \
            --min-forks "${{ github.event.inputs.min_forks }}" \
            --output "${{ github.event.inputs.output_file }}"

      - name: Upload search results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: search-results
          path: ${{ github.event.inputs.output_file }}
